name: tag-testapp-build-yaml

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag name
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set Maven version
        run: mvn --batch-mode versions:set -DnewVersion=${{ env.TAG_NAME }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file_glob: true
            file: target/*.war
            tag: ${{ github.ref }}
            
  test-deploy:
    name: test-deploy-job-name
    needs: build
    runs-on: ubuntu-latest
    environment: test_deploy
    
    steps:
        - name: Get the tag name
          run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        - name: Download deployment artifact
          run: mkdir artifacts
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            version: "tags/${{ env.TAG_NAME }}"
            file: "test-webapp-${{ env.TAG_NAME }}.war"
            target: "artifacts/test-webapp-${{ env.TAG_NAME }}.war"
            token: ${{ secrets.GITHUB_TOKEN }}
         
