name: testapp-build-yaml

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set Maven version
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.ref }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file_glob: true
            file: target/*.war
            tag: ${{ github.ref }}        
